FROM microsoft/mssql-server-linux:2017-latest

#RUN apt-get update
#RUN ACCEPT_EULA=Y apt-get install -y \
#    mssql-tools

#RUN apt-get install -y locales \
#    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
#    && locale-gen

#ENV PATH="/opt/mssql-tools/bin:${PATH}"